name = "BiophysicalGeometry"
uuid = "06c61620-4f66-4020-a018-07befe374221"
authors = ["Michael Kearney, Rafael Schouten"]
version = "0.1.0"

[deps]
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
Aqua = "0.8"
CSV = "0.10"
DataFrames = "1"
Roots = "2.2.7"
SafeTestsets = "0.1"
Test = "1"
Unitful = "1"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Roots", "SafeTestsets", "Test"]
